### ISSUE TITLE
Hugo build failing on Cloudflare pages

### ISSUE THREAD

**Issue by arnaudschlupp** [bep/hugo-testing-tailwindcss-v4#6]
When trying to build it on Cloudflare workers, I get the following error:

```
16:00:30.236 | Error: error building site: POSTCSS: failed to transform "/css/main.css" (text/css): Error: Loading PostCSS Plugin failed: Cannot find module '@tailwindcss/oxide-linux-x64-gnu'
-- | --
16:00:30.236 | Require stack:
16:00:30.236 | - /opt/buildhome/repo/node_modules/@tailwindcss/oxide/index.js
16:00:30.236 | - /opt/buildhome/repo/node_modules/@tailwindcss/postcss/dist/index.js
16:00:30.237 |  
16:00:30.237 | (@/opt/buildhome/repo/postcss.config.js)
16:00:30.237 | at load (/opt/buildhome/repo/node_modules/postcss-load-config/src/plugins.js:28:11)
16:00:30.237 | at async Promise.all (index 0)
16:00:30.237 | at async plugins (/opt/buildhome/repo/node_modules/postcss-load-config/src/plugins.js:57:12)
16:00:30.237 | at async processResult (/opt/buildhome/repo/node_modules/postcss-load-config/src/index.js:39:14)
16:00:30.237 | at async Promise.all (index 0)
```

<img width="1232" alt="Screenshot 2024-12-30 at 10 20 01" src="https://github.com/user-attachments/assets/731e68bb-cc9c-48e5-acdd-8d3ec0f6d2a8" />

I think the issue is on Tailwind sides; but maybe you know more about it 🙇

**Comment by bep** [comment]
>I think the issue is on Tailwind sides; but maybe you know more about it 🙇

I don't, but I'm pretty sure it's not Hugo related.
